# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5a7c8c98560866b8492d6661cdc2475fd2cdb8863ffcd1b2836d2f83d79eee0f2382d8cedc8410ad23eebfc4f9afcfdb1c05152b5343b2c754390096320b9e6

test:
  secret_key_base: 9d8dfae3a61750608c7224360f6ec47aa223395157bd523f5f4034a78536c9678114f72f6f5fe5e46738f5612afb6bee39b2e7b63b2a71dfa5023834a1d464b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
